modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="exoplanet_exploration"
version="1.0.0"
displayName="Exoplanet Exploration"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="xingrui, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.exoplanet_exploration]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.exoplanet_exploration]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.exoplanet_exploration]]
    modId="biomeswevegone"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration